# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            Hybrid room
subtitle:         A surfer/swimmer/nomad programmer/extreme sports lover
description:      A surfer/swimmer/nomad programmer/extreme sports lover
keywords:         A surfer/swimmer/nomad programmer/extreme sports lover
language:         "en" # default language of the blog. Language codes: http://www.w3schools.com/tags/ref_language_codes.asp

baseurl:           # the subpath of your site, e.g. /blog
url:              "" # the base hostname & protocol for your site. Have a look at robots.txt as well!
permalink:        /blog/:categories/:title
cover:            /assets/cover-teahupoo.jpg
disqus_shortname: ""

# Build settings
baseurl:
sass:
    style: compressed
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
include: ['_pages']
exclude: [vendor, "developer-tools"]
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]
  blanklines: true
  startings: [head, body]
